import { randomUUID } from "node:crypto";
import pg from "pg";
import type { UnusualContract } from "./cboe.js";
import { dateTimeInNewYork, DAY_UNUSUAL_VOLUME_RATIO, MIN_UNUSUAL_SIZE, plusMonths, summarizeFlow, todayInNewYork } from "./domain.js";

const { Pool } = pg;

export type ActivityQuery = {
  page: number;
  pageSize: number;
  sort: string;
  order: "ASC" | "DESC";
  listing: string;
  q: string;
};

let pool: pg.Pool | null = null;
const sweepOwner = randomUUID();

export function getPool(): pg.Pool {
  if (pool) return pool;
  const connectionString = process.env.DATABASE_URL?.trim();
  if (!connectionString) throw new Error("DATABASE_URL is not set");
  pool = new Pool({ connectionString, max: 4 });
  return pool;
}

export async function migrateNeon(): Promise<void> {
  const db = getPool();
  await db.query(`
    CREATE TABLE IF NOT EXISTS unusual_contracts (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      option_symbol TEXT UNIQUE NOT NULL,
      occurred_at TEXT,
      ticker TEXT NOT NULL,
      option_type TEXT NOT NULL,
      direction TEXT NOT NULL,
      strike DOUBLE PRECISION,
      expiration TEXT,
      dte INTEGER,
      volume INTEGER,
      open_interest INTEGER,
      volume_oi_ratio DOUBLE PRECISION,
      estimated_premium DOUBLE PRECISION,
      bid DOUBLE PRECISION,
      ask DOUBLE PRECISION,
      last DOUBLE PRECISION,
      underlying_price DOUBLE PRECISION,
      in_sp500 INTEGER NOT NULL,
      in_nasdaq INTEGER NOT NULL,
      source TEXT NOT NULL,
      scan_id TEXT NOT NULL
    )
  `);
  await db.query(`
    CREATE TABLE IF NOT EXISTS scan_state (
      id INTEGER PRIMARY KEY,
      last_updated_at TIMESTAMPTZ,
      trade_since TEXT
    )
  `);
  await db.query(`ALTER TABLE scan_state ADD COLUMN IF NOT EXISTS sweep_owner TEXT`);
  await db.query(`ALTER TABLE scan_state ADD COLUMN IF NOT EXISTS sweep_heartbeat TIMESTAMPTZ`);
  await db.query(`INSERT INTO scan_state (id) VALUES (1) ON CONFLICT (id) DO NOTHING`);
  await db.query(`CREATE INDEX IF NOT EXISTS unusual_contracts_occurred_at ON unusual_contracts (occurred_at DESC)`);
  await db.query(`CREATE INDEX IF NOT EXISTS unusual_contracts_ticker ON unusual_contracts (ticker)`);
}

export async function getTradeWatermark(): Promise<string | null> {
  const result = await getPool().query<{ trade_since: string | null }>("SELECT trade_since FROM scan_state WHERE id = 1");
  return result.rows[0]?.trade_since ?? null;
}

export async function getLastUpdatedAt(): Promise<string | null> {
  const result = await getPool().query<{ last_updated_at: Date | null }>(
    "SELECT last_updated_at FROM scan_state WHERE id = 1",
  );
  const value = result.rows[0]?.last_updated_at;
  return value ? dateTimeInNewYork(new Date(value)) : null;
}

export async function markScanFinished(tradeSince: string): Promise<void> {
  await getPool().query(
    `UPDATE scan_state
     SET last_updated_at = NOW(), trade_since = $1, sweep_owner = NULL, sweep_heartbeat = NULL
     WHERE id = 1 AND (sweep_owner IS NULL OR sweep_owner = $2)`,
    [tradeSince, sweepOwner],
  );
}

export async function rememberSavedSweep(tradeSince: string): Promise<void> {
  await getPool().query(
    `UPDATE scan_state
     SET last_updated_at = COALESCE(last_updated_at, NOW()),
         trade_since = COALESCE(trade_since, $1)
     WHERE id = 1`,
    [tradeSince],
  );
}

export async function tryAcquireSweep(): Promise<boolean> {
  const result = await getPool().query(
    `UPDATE scan_state
     SET sweep_owner = $1, sweep_heartbeat = NOW()
     WHERE id = 1
       AND (
         sweep_owner IS NULL
         OR sweep_owner = $1
         OR sweep_heartbeat IS NULL
         OR sweep_heartbeat < NOW() - INTERVAL '90 seconds'
       )
     RETURNING id`,
    [sweepOwner],
  );
  return (result.rowCount ?? 0) > 0;
}

export async function touchSweep(): Promise<void> {
  await getPool().query("UPDATE scan_state SET sweep_heartbeat = NOW() WHERE id = 1 AND sweep_owner = $1", [sweepOwner]);
}

export async function releaseSweep(): Promise<void> {
  await getPool().query(
    "UPDATE scan_state SET sweep_owner = NULL, sweep_heartbeat = NULL WHERE id = 1 AND sweep_owner = $1",
    [sweepOwner],
  );
}

export async function countVisibleContracts(): Promise<{ count: number; last: string | null }> {
  const { where, params } = visibleFilter([]);
  const result = await getPool().query<{ count: string; last: string | null }>(
    `SELECT COUNT(*)::int AS count, MAX(occurred_at) AS last FROM unusual_contracts ${where}`,
    params,
  );
  return { count: Number(result.rows[0]?.count ?? 0), last: result.rows[0]?.last ?? null };
}

export async function upsertContracts(
  contracts: UnusualContract[],
  ticker: string,
  inSp500: number,
  inNasdaq: number,
  scanId: string,
  watermark: string | null,
): Promise<void> {
  void watermark;
  const fresh = contracts.filter((contract) => {
    if (!contract.occurredAt) return false;
    return (contract.estimatedPremium ?? 0) >= MIN_UNUSUAL_SIZE;
  });
  if (fresh.length === 0) return;
  const db = getPool();
  const client = await db.connect();
  try {
    await client.query("BEGIN");
    for (const contract of fresh) {
      await client.query(
        `INSERT INTO unusual_contracts (
           option_symbol, occurred_at, ticker, option_type, direction, strike, expiration, dte,
           volume, open_interest, volume_oi_ratio, estimated_premium, bid, ask, last, underlying_price,
           in_sp500, in_nasdaq, source, scan_id
         ) VALUES (
           $1, $2, $3, $4, $5, $6, $7, $8,
           $9, $10, $11, $12, $13, $14, $15, $16,
           $17, $18, $19, $20
         )
         ON CONFLICT (option_symbol) DO UPDATE SET
           occurred_at = EXCLUDED.occurred_at,
           ticker = EXCLUDED.ticker,
           option_type = EXCLUDED.option_type,
           direction = EXCLUDED.direction,
           strike = EXCLUDED.strike,
           expiration = EXCLUDED.expiration,
           dte = EXCLUDED.dte,
           volume = EXCLUDED.volume,
           open_interest = EXCLUDED.open_interest,
           volume_oi_ratio = EXCLUDED.volume_oi_ratio,
           estimated_premium = EXCLUDED.estimated_premium,
           bid = EXCLUDED.bid,
           ask = EXCLUDED.ask,
           last = EXCLUDED.last,
           underlying_price = EXCLUDED.underlying_price,
           in_sp500 = EXCLUDED.in_sp500,
           in_nasdaq = EXCLUDED.in_nasdaq,
           source = EXCLUDED.source,
           scan_id = EXCLUDED.scan_id`,
        [
          contract.optionSymbol,
          contract.occurredAt,
          ticker,
          contract.optionType,
          contract.direction,
          contract.strike,
          contract.expiration,
          contract.dte,
          contract.volume,
          contract.openInterest,
          contract.volumeOiRatio,
          contract.estimatedPremium,
          contract.bid,
          contract.ask,
          contract.last,
          contract.underlyingPrice,
          inSp500,
          inNasdaq,
          contract.source,
          scanId,
        ],
      );
    }
    await client.query("COMMIT");
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  } finally {
    client.release();
  }
}

const SORTS: Record<string, string> = {
  occurredAt: "occurred_at",
  ticker: "ticker",
  optionType: "option_type",
  strike: "strike",
  expiration: "expiration",
  dte: "dte",
  volume: "volume",
  openInterest: "open_interest",
  volumeOiRatio: "volume_oi_ratio",
  estimatedPremium: "estimated_premium",
  bid: "bid",
  ask: "ask",
  last: "last",
};

export async function listActivity(query: ActivityQuery): Promise<{ total: number; rows: unknown[]; sort: string }> {
  const sort = SORTS[query.sort] ? query.sort : "occurredAt";
  const column = SORTS[sort] ?? "occurred_at";
  const order = query.order === "ASC" ? "ASC" : "DESC";
  const params: Array<string | number> = [];
  const filters = visibleFilter(params);
  if (query.listing === "sp500") {
    params.push(1);
    filters.clauses.push(`in_sp500 = $${params.length}`);
  } else if (query.listing === "nasdaq") {
    params.push(1);
    filters.clauses.push(`in_nasdaq = $${params.length}`);
  }
  if (query.q) {
    params.push(`${query.q.replace(/[\\%_]/g, "\\$&")}%`);
    filters.clauses.push(`ticker LIKE $${params.length} ESCAPE '\\'`);
  }
  const where = filters.clauses.length ? `WHERE ${filters.clauses.join(" AND ")}` : "";
  const db = getPool();
  const total = await db.query<{ count: string }>(`SELECT COUNT(*)::int AS count FROM unusual_contracts ${where}`, params);
  params.push(query.pageSize, (query.page - 1) * query.pageSize);
  const rows = await db.query(
    `SELECT id, option_symbol AS "optionSymbol", occurred_at AS "occurredAt", ticker,
            option_type AS "optionType", direction, strike, expiration, dte, volume,
            open_interest AS "openInterest", volume_oi_ratio AS "volumeOiRatio",
            estimated_premium AS "estimatedPremium", bid, ask, last,
            underlying_price AS "underlyingPrice", source,
            (volume_oi_ratio >= ${DAY_UNUSUAL_VOLUME_RATIO}) AS "dayUnusual"
     FROM unusual_contracts
     ${where}
     ORDER BY CASE WHEN volume_oi_ratio >= ${DAY_UNUSUAL_VOLUME_RATIO} THEN 0 ELSE 1 END,
              CASE WHEN volume_oi_ratio >= ${DAY_UNUSUAL_VOLUME_RATIO} THEN volume_oi_ratio END DESC NULLS LAST,
              ${column} ${order} NULLS LAST, ticker ASC
     LIMIT $${params.length - 1} OFFSET $${params.length}`,
    params,
  );
  return { total: Number(total.rows[0]?.count ?? 0), rows: rows.rows, sort };
}

export async function tickerFlow(ticker: string): Promise<{
  ticker: string;
  underlyingPrice: number | null;
  weekly: ReturnType<typeof summarizeFlow>["weekly"];
  monthly: ReturnType<typeof summarizeFlow>["monthly"];
}> {
  const today = todayInNewYork();
  const oldest = plusMonths(today, -6);
  const result = await getPool().query<{
    optionType: "call" | "put";
    expiration: string;
    estimatedPremium: number | null;
    underlyingPrice: number | null;
  }>(
    `SELECT option_type AS "optionType", expiration, estimated_premium AS "estimatedPremium",
            underlying_price AS "underlyingPrice"
     FROM unusual_contracts
     WHERE ticker = $1
       AND estimated_premium >= $2
       AND open_interest > 0
       AND expiration >= $3
       AND occurred_at IS NOT NULL
       AND substr(occurred_at, 1, 10) >= $4`,
    [ticker, MIN_UNUSUAL_SIZE, today, oldest],
  );
  const summary = summarizeFlow(result.rows, today);
  const underlyingPrice = result.rows.reduce<number | null>((price, row) => price ?? row.underlyingPrice, null);
  return { ticker, underlyingPrice, ...summary };
}

function visibleFilter(params: Array<string | number>): { where: string; clauses: string[]; params: Array<string | number> } {
  const today = todayInNewYork();
  const oldest = plusMonths(today, -6);
  params.push(MIN_UNUSUAL_SIZE, today, oldest);
  const clauses = [
    `estimated_premium >= $${params.length - 2}`,
    "open_interest > 0",
    `expiration >= $${params.length - 1}`,
    "occurred_at IS NOT NULL",
    `substr(occurred_at, 1, 10) >= $${params.length}`,
  ];
  return { where: `WHERE ${clauses.join(" AND ")}`, clauses, params };
}
